from crewai import Task
from agents import agents

def tasks(llm, job_desire, Experience, resume_content):
    '''
    job__research - Find the relevant skills, projects and experience
    resume_analysis- understand the report and the resume based on this make a swot analysis
    '''

    verify_resume, job_researcher, resume_agent, resume_analyser  = agents(llm)

    research_task = Task(
        description=f'For Job Position of Desire: {job_desire} research to identify the current market requirements for a person at the job including the relevant skills, some unique research projects or common projects along with what experience would be required. For searching query use ACTION INPUT KEY as "search_query"',
        expected_output='A report on what are the skills required and some unique real time projects that can be there which enhances the chance of a person to get a job',
        agent=job_researcher
    )

    resume_analysis_task = Task(
        description=f'Resume Content: {resume_content} \n Analyse the resume provided with {Experience} and the report of job_requirements_researcher to provide a detailed SWOT analysis report on the resume along with the Resume Match Percentage and Suggestions to improve',
        expected_output='A JSON formatted report as follows: "candidate": candidate, "strengths":[strengths], "weaknesses":[weaknesses], "opportunities":[opportunities], "threats":[threats], "resume_match_percentage": resume_match_percentage, "suggestions": "suggestions"',
        agent=resume_analyser,
        output_file='resume-report/resume_review.json'
    )

        # Task for verify_resume agent
    verify_resume_task = Task(
        description='Verify the resume\'s format, design, and content to ensure it meets industry standards and is easy to read.',
        expected_output='A boolean value indicating whether the resume is verified (True) or not (False).',
        agent=verify_resume
    )

        # Tasks for resume_agent
    analyze_requirements_task = Task(
        description='Analyze the job requirements report generated by the job_researcher agent to identify the key skills, projects, and experience required for the desired job.',
        expected_output='A list of the most important skills, projects, and experience required for the desired job.',
        agent=resume_agent
    )

    modify_resume_task = Task(
        description='Modify the resume to align with the identified key skills, projects, and experience.',
        expected_output='A modified version of the resume that highlights the key skills, projects, and experience required for the desired job.',
        agent=resume_agent
    )

    return verify_resume_task, research_task, analyze_requirements_task, modify_resume_task, resume_analysis_task